### ISSUE TITLE
Logos in Login Screen Are Not Centered

### ISSUE THREAD

**Issue by Archmonger** [Burry/organizr-v2-plex-theme#17]
Currently logos that are square and less than 320px wide don't get centered. <br/>
Example:<br/>

![image](https://user-images.githubusercontent.com/16909269/51081430-1f794680-16a4-11e9-827e-052952edec95.png)

A simple fix adding this line of CSS to the Plex theme<br/>
```css
.login-box .white-box .form-horizontal .text-center {
    width: 320px;
}
```
